Models/ErrorViewModel.cs
namespace NBA_Stats.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PlayerModel.cs
namespace NBA_Stats.Models
{
    public class PlayerModel
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string position { get; set; }
        public string height_feet { get; set; }
        public string height_inches { get; set; }
        public string weight_pounds { get; set; }
        public string headshot_url { get; set; }
        public string season { get; set; }

        public TeamModel team { get; set; }
        public SeasonAvgModel stats { get; set; }
    }

    public class PlayerListModel
    {
        public PlayerListModel()
        {
            players = new List<PlayerModel>();
        }
        public List<PlayerModel> players { get; set; }
    }

    public class PlayerSearchModel
    {

        public PlayerSearchModel()
        {
            GUID = Guid.NewGuid().ToString();
        }

        public bool includeScripts { get; set; }
        public bool isRemovable { get; set; }
        public string GUID { get; set; }

    }

    public class PlayerHeadshotModel
    {
        public string fullName { get; set; }
        public int id { get; set; }
        public int personID { get; set; }
    }

    


    public class SeasonAvgModel
    {
        public int player_id { get; set; }
        public int season { get; set; }
        public int games_played { get; set; }
        public decimal fga { get; set; }
        public decimal fgm { get; set; }
        public decimal fg3m { get; set; }
        public decimal pts { get; set; }
        public decimal reb { get; set; }
        public decimal ast { get; set; }
        public decimal stl { get; set; }
        public decimal blk { get; set; }
        public decimal fg_pct { get; set; }
        public decimal eff_fg_pct
        {
            get
            {
                return Decimal.Round(((fgm * games_played) + ((decimal)0.5 * fg3m)) / (games_played * fga), 3);
            }
        }
    }

    public class SeasonAvgDataModel
    {
        public List<SeasonAvgModel> data { get; set; }
    }
}

Models/TeamModel.cs
namespace NBA_Stats.Models
{
    public class TeamModel
    {
        public int id { get; set; }
        public string full_name { get; set; } = string.Empty;
        public string city { get; set; } = string.Empty;
        public string name { get; set; } = string.Empty;
        public string abbreviation { get; set; } = string.Empty;
        public string conference { get; set; } = string.Empty;
        public string logo_url
        {
            get
            {
                return $"https://i.cdn.turner.com/nba/nba/.element/img/1.0/teamsites/logos/teamlogos_500x500/{abbreviation.ToLower()}.png";
            }
        }

        public List<Team_Record_Date>? Team_Record_History { get; set; }

    }

    public class Team_Record_Date
    {

        public DateTime Date { get; set; }
        public string date_2 { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public double Winning_Pct 
        {
            get
            {
                int totalGames = Wins + Losses;
                double winPct = 0.5;
                if (totalGames > 0)
                {
                    winPct = (double)Wins / totalGames;
                }


                return winPct;
            }
        }
    }

    public class GamesResultModel
    {
        public List<GameModel> Data { get; set; } = new List<GameModel>();
        public MetaModel Meta { get; set; } = new MetaModel();
    }

    public class GameModel
    {
        public int id { get; set; }
        public DateTime date { get; set; }
        public int home_team_score { get; set; }
        public int visitor_team_score { get; set; }
        public int season { get; set; }
        public int period { get; set; }
        public string status { get; set; }
        public string time { get; set; }
        public bool postseason { get; set; }
        public TeamModel home_team { get; set; } 
        public TeamModel visitor_team { get; set; }
    }

    public class MetaModel
    {
        public int total_pages { get; set; }
        public int current_page { get; set; }
        public int? next_page { get; set; }
        public int per_page { get; set; }
        public int total_count { get; set; }

    }
}

Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace NBA_Stats.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            ViewBag.UseSelect2 = false;
            ViewBag.UseD3 = false;
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NBA_Stats.Models;
using System.Diagnostics;

namespace NBA_Stats.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using NBA_Stats.Models;
using NBA_Stats.Services;

namespace NBA_Stats.Controllers
{
    public class PlayerController : BaseController
    {
        private readonly PlayerService ps = new PlayerService();

        public ActionResult Player_Search()
        {
            return View();
        }

        public JsonResult Get_Random_Player()
        {
            var random = new Random();
            List<PlayerHeadshotModel> playersWithHeadshots = ps.Players_With_Headshots();
            int index = random.Next(playersWithHeadshots.Count);

            return Json(playersWithHeadshots[index]);
        }

        public PartialViewResult Get_Player(int playerID)
        {
            PlayerModel player = ps.Get_Player(playerID);

            return PartialView("_player", player);

        }

        public PartialViewResult Get_Stats(int playerID, int season)
        {
            SeasonAvgModel stats = new SeasonAvgModel();
            stats = ps.Get_Player_Stats(playerID, season);
            return PartialView("_playerStats", stats);
        }

        public ActionResult Player_Comparison(string id)
        {
            return View();
        }

        public JsonResult Get_Player_Comparison(string players, string seasons)
        {
            PlayerListModel mod = new PlayerListModel();

            string[] playersArray = players.Split(',');
            string[] seasonsArray = seasons.Split(',');

            for (int i = 0; i < playersArray.Length; i++)
            {
                PlayerModel player = ps.Get_Player(int.Parse(playersArray[i]));
                player.stats = ps.Get_Player_Stats(int.Parse(playersArray[i]), int.Parse(seasonsArray[i]));
                mod.players.Add(player);

            }

            return Json(mod);
        }
    }
}

Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using NBA_Stats.Models;
using NBA_Stats.Services;

namespace NBA_Stats.Controllers
{
    public class TeamController : BaseController
    {
        private readonly TeamService ts = new TeamService();
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Team_Details(int id)
        {
            TeamModel team = new TeamModel();
            team = ts.Get_Team(id);

            return View(team);
        }

        public JsonResult Team_Record_History(int id, int season = 2021)
        {
            TeamModel team = new TeamModel();
            team.id = id;

            team.Team_Record_History = ts.Get_Team_Record(team.id, season);

            return Json(team.Team_Record_History);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Player/Player_Comparison.cshtml
@using NBA_Stats.Models;
@{
    ViewBag.Title = "Player Comparison";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.UseSelect2 = true;
    ViewBag.UseD3 = true;
}

<h2>Player Comparison</h2>
<style>
    .extraCompare {
        display: none;
    }

    .max .bar {
        fill: #69b3a2;
    }

    text.label {
        font-size: 16px;
        font-weight: 500;
    }

    .barChart {
        display: flex;
        align-items: center;
        justify-content: center;
    }

</style>

@await Html.PartialAsync("_playerSelect2Search", new PlayerSearchModel { includeScripts = true, isRemovable = false })
<hr />
@await Html.PartialAsync("_playerSelect2Search", new PlayerSearchModel { includeScripts = false, isRemovable = false })
<hr />
@for (int i = 0; i < 3; i++)
{
    <div class="extraCompare">
        @await Html.PartialAsync("_playerSelect2Search", new PlayerSearchModel { includeScripts = false, isRemovable = true })
        <hr />
    </div>
}


<div class="row">
    <div class="col-md-11 offset-md-1">
        <button id="addCompareBtn" type="button" class="btn btn-outline-primary"><i class="fa fa-plus"></i> Add player</button>
    </div>
</div>
<div class="row justify-content-center my-4">
    <div class="col col-md-8 d-grid">
        <button type="button" id=btnCompare class="btn btn-primary" onclick="comparePlayers()">Compare Selected Players</button>
        <button type="button" id="btnCompareLoading" class="btn btn-primary" style=display:none;><i class="fas fa-spinner fa-pulse"></i> Getting stats</button>
    </div>
</div>


<div id="divStatCharts" class="row gy-5">
    <div class="col-lg-6">
        <div class="barChart" id="chartPoints"></div>
    </div>
    <div class="col-lg-6">
        <div class="barChart" id="chartRebounds"></div>
    </div>
    <div class="col-lg-6">
        <div class="barChart" id="chartAssists"></div>
    </div>
    <div class="col-lg-6">
        <div class="barChart" id="chartFieldGoalPct"></div>
    </div>
</div>
<div id="my_dataviz"></div>

@section Scripts{

<script type="text/javascript">

        $("#addCompareBtn").click(function () {

            $(".extraCompare:hidden:first").slideToggle();

            if (!$(".extraCompare:hidden").length) {
                $("#addCompareBtn").hide();
            }

        });

        $('.btnGetRandomPlayer').click(function () {

            var guid = $(this).attr("id").split('_')[1];
            var $selectInput = $('#select2_' + guid);

            $.ajax({
                    type: "POST",
                    url: '@Url.Action("Get_Random_Player", "player")',
                    dataType:'json',
                success: function (data) {
                    var option = new Option(data.fullName, data.id, true, true);

                    $selectInput.append(option).trigger('change');

                    $selectInput.trigger({
                        type: 'select2:select',
                        params: {
                            data: data
                        }
                    });
                }
            });
        });

        function comparePlayers() {
            var players = [];
            var seasons = [];
            $('.inputPlayerSearch:visible').each(function () {
                var playerID = $(this).val();
                if (playerID) {
                    players.push(playerID);
                    seasons.push('2021');
                }

            });

            if (players.length < 2) {
                Swal.fire({
                    title: 'Please select at least 2 players to compare.',
                    icon: 'warning',
                    confirmButtonText: 'OK'
                })
            }
            else{


                $btn = $('#btnCompare');
                $btnLoading = $('#btnCompareLoading');

                $btn.hide();
                $btnLoading.show();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Get_Player_Comparison", "player")',
                    data: {
                        "players": players.join(','),
                        "seasons": seasons.join(',')
                    },
                    success: function (data) {
                        d3.selectAll("svg").remove();
                        $([document.documentElement, document.body]).animate({
                            scrollTop: $("#divStatCharts").offset().top
                        }, 2000);
                        showPlayerCompare(data.players);
                        $btnLoading.hide();
                        $btn.show();
                }
            });
            }
        }

        function showPlayerCompare(sample) {
            createHorizontalBarChart("#chartPoints", sample, 'Points', 'pts', 35);
            createHorizontalBarChart("#chartRebounds", sample, 'Rebounds', 'reb', 16);
            createHorizontalBarChart("#chartAssists", sample, 'Assists', 'ast', 12);
            createHorizontalBarChart("#chartFieldGoalPct", sample, 'Field Goal %', 'fg_pct', 70, true);
        }


        function createHorizontalBarChart(chartID, data, label, stat, maxVal, isPct = false) {


            // set the dimensions and margins of the graph
            const margin = { top: 40, right: 60, bottom: 40, left: 120 },
                width = 460 - margin.left - margin.right,
                innerHeight = (data.length * 50),
                height = innerHeight + margin.top + margin.bottom;

            const max = d3.max(data, function (d) { return getStatValue(d) });

            // append the svg object to the body of the page
            const svg = d3.select(chartID)
                .append("svg")
                .attr("width", width + margin.left + margin.right)
                .attr("height", height)
                .append("g")
                .attr("transform", `translate(${margin.left}, ${margin.top})`);




            // Add X axis
            const xAxis = d3.scaleLinear()
                .domain([0, Math.max(maxVal, max)])
                .range([0, width]);

            svg.append("g")
                .attr("transform", `translate(0, ${innerHeight})`)
                .call(d3.axisBottom(xAxis))
                .selectAll("text")
                .attr("transform", "translate(-10,0)rotate(-45)")
                .style("text-anchor", "end");

            // Y axis
            const yAxis = d3.scaleBand()
                .range([0, innerHeight])
                .domain(data.map(d => d.first_name + " " + d.last_name + " " + d.stats.season))
                .padding(.015);


            const gyAxis = svg.append("g")
                .call(d3.axisLeft(yAxis).tickSize([0]))
                .selectAll(".tick text")
                .call(wrap, margin.left);

            gyAxis.select('.domain')
                .attr('stroke-width', 0);



            var bars = svg.selectAll(".bar")
                .data(data)
                .enter()
                .append("g")

            //append rects
            bars.append("rect")
                .attr("class", "bar")
                .attr("y", function (d) {
                    return yAxis(d.first_name + " " + d.last_name + " " + d.stats.season);
                })
                .attr("height", yAxis.bandwidth())
                .attr("x", 0)
                .attr("fill", "#AAB8C4")

                .transition()
                .duration(2000)
                .attr("width", function (d) {
                    return xAxis(getStatValue(d));
                });

            bars.attr('opacity', 0.8);

            bars.on("mouseover", function (event, d) {
                d3.select(this)
                    //.transition()
                    //.duration(300)
                    .attr('opacity', 1)
                })
                .on("mouseout", function (event, d) {
                    d3.select(this)
                        //.transition()
                        //.duration(300)
                        .attr('opacity', 0.8)
                });





            var maxBar = bars.filter(function (d) { return getStatValue(d) === max });

            maxBar.selectAll("rect").transition().duration(2000)
                .attr("fill", "#69b3a2")
                .attr("width", function (d) {
                    return xAxis(getStatValue(d));
                });

            //add a value label to the right of each bar
            var valueLabel = bars.append("text")
                .attr("class", "label")
                .attr("y", function (d) {
                    return yAxis(d.first_name + " " + d.last_name + " " + d.stats.season) + yAxis.bandwidth() / 2 + 4;
                })
                .attr("x", function (d) {
                    return xAxis(getStatValue(d)) + 3;
                })
                .text(function (d) {
                    return getStatValue(d) + (isPct ? "%" : "");
                })
                .attr("opacity", 0);

            valueLabel.transition().duration(3000)
                .attr("opacity", 0.8);


            svg.append('text')
                .attr('class', 'label')
                .attr('x', width / 2)
                .attr('y', innerHeight + margin.top)
                .attr('text-anchor', 'middle')
                .text(label)

            function getStatValue(d) {
                var statValue = d.stats[stat];
                if (isPct) {
                    statValue = (statValue * 100).toFixed(1);
                }

                return statValue;
            }

            function wrap(text) {
                var labelMarginRight = 5;
                text.each(function () {
                    var text = d3.select(this),
                        words = text.text().split(/\s+/).reverse(),
                        word,
                        line = [],
                        lineNumber = 0,
                        lineHeight = 1.1, // ems
                        y = text.attr("y"),
                        dy = parseFloat(text.attr("dy")),
                        tspan = text.text(null).append("tspan").attr("x", -labelMarginRight).attr("y", y).attr("dy", dy - 0.5 + "em");
                    while (word = words.pop()) {
                        line.push(word);
                        tspan.text(line.join(" "));
                        if (!isNaN(word)) {
                            line.pop();
                            tspan.text(line.join(" "));
                            line = [word];
                            tspan = text.append("tspan").attr("x", -labelMarginRight).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
                        }
                    }
                });
            }
        }
</script>
}

Views/Player/Player_Search.cshtml
@using NBA_Stats.Models;
@{
    ViewBag.Title = "Player Stats";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.UseSelect2 = true;
    ViewBag.UseD3 = true;
}


<style>
    .grid line {
        stroke: lightgrey;
        stroke-opacity: 0.7;
        shape-rendering: crispEdges;
    }

    .grid path {
        stroke-width: 0;
    }

    #playerTitle {
        overflow: auto;
        width: 400px;
        margin: 0 auto;
    }

    #teamLogo {
        float: left;
        width: 100px;
        height: 100px;
    }


    #positionTeamSubHeader {
        font-size: 1.5rem;
    }

    #divSeasonStats {
        font-size: 1.5rem;
        line-height: 2;
    }

    .select2-search__field {
        max-width: 100%;
    }

    #divStats {
        margin: 30px 10px 10px 10px;
    }

    #divRightSideStats {
        margin: 0 auto;
    }


</style>


<h2>Player Stats</h2>



@await Html.PartialAsync("_playerSelect2Search", new PlayerSearchModel { includeScripts = true, isRemovable = false })
<hr />

<div id="results"></div>

@section Scripts{
    

    <script type="text/javascript">

        $('.inputPlayerSearch').on('change.select2', function (e) {
            var playerID = $(this).val();
            getPlayer(playerID);
        });

        $('.btnGetRandomPlayer').click(function () {
            getPlayer(-1);
        });

        function getPlayer(playerID) {
            $.ajax({
                    type: "POST",
                    url: '@Url.Action("Get_Player", "player")',
                    data: {
                        "playerID": playerID
                    },
                success: function (view) {
                    d3.select("svg").remove();
                    $('#results').html(view);
                    if (playerID < 0) {
                        $('#inputPlayerSearch').text("");
                    }
                    getStats();
                }
            });
        }





    </script>

}

Views/Player/_player.cshtml
@model NBA_Stats.Models.PlayerModel

@{
    List<SelectListItem> seasons = new List<SelectListItem>();
    for (int i = 2021; i >= 2000; i--)
    {
        seasons.Add(new SelectListItem() { Value = i.ToString(), Text = i.ToString() });
    };
}

<div class="row">
    <div class="col-lg-6">
        <div id="playerTitle">

            <img id="teamLogo" src="@Model.team.logo_url" />
            <h2 id="playerName"> @Model.first_name @Model.last_name</h2>

            <span id="positionTeamSubHeader">@Model.position | @Model.team.full_name</span>
            <br />
            @if (!string.IsNullOrEmpty(Model.height_feet))
            {

                <div id="playerHeadshot"></div>

            }
            else
            {

                <span>Height: ???</span>
                <img src="@Model.headshot_url" style="display:block; margin:auto;" />
            }

        </div>
    </div>
    <div id="divRightSideStats" class="col-lg-4">
        <label class="col-form-label">
            Select Season:
        </label>
        @Html.DropDownList("seasons", seasons, new { @class = "form-select", onchange = "getStats()", id = "ddlSeason" })
        <div id="divStats"></div>
    </div>
</div>




@if (!string.IsNullOrEmpty(Model.height_feet))
{

    <script type="text/javascript">



        var margin = { top: 30, right: 30, bottom: 30, left: 40 },k
            width = 400 - margin.left - margin.right,
            height = 400 - margin.top - margin.bottom;

        // append the svg object to the body of the page
            var svg = d3.select("#playerHeadshot")
                .append("svg")
                .attr("width", width + margin.left + margin.right)
                .attr("height", height + margin.top + margin.bottom)
                .append("g")
                .attr("transform", `translate(${margin.left},${margin.top})`);



        var y = d3.scaleLinear()
            .domain([5, 7.25])
            .range([height, 0]);

        var y_axis = d3.axisLeft().scale(y)
            .tickValues([5, 5.25, 5.5, 5.75, 6, 6.25, 6.5, 6.75, 7, 7.25])
            .tickFormat((d, i) => [`5'`, `5' 3"`, `5' 6"`, `5' 9"`, `6'`, `6' 3"`, `6' 6"`, `6' 9"`, `7'`, `7' 3"`][i])
            .tickSize(-width);

        var gYAxis = svg.append("g")
            .call(y_axis);

        gYAxis.selectAll('.tick line').attr('opacity', 0.1);
        gYAxis.select('.domain').attr('opacity', 0.1);




            svg.append("svg:image")

            .attr('y', height - (height / 27) * (@Model.height_feet * 12 + @Model.height_inches - 60) - 6)
            .attr('x', 20)
            .attr('width', 260)
            .attr('height', 190)
            //.attr("transform", `translate(${margin.left},${margin.top})`)
            .attr("xlink:href", "@Model.headshot_url");

        svg.append("text")

            .attr('y', height - (height / 27) * (@Model.height_feet * 12 + @Model.height_inches - 60) - 13)
            .attr('x', 180)
            //.attr("transform", `translate(${margin.left},${margin.top})`)
            .text(`@Model.height_feet' @Model.height_inches" (@Model.weight_pounds lbs)`);


    </script>
}

<script type="text/javascript">

    function getStats() {
             $.ajax({
                type: "POST",
                url: '@Url.Action("Get_Stats", "player")',
                data: {
                    "playerID": '@Model.id',
                    "season": $('#ddlSeason :selected').val()
                },
                success: function (view) {
                $('#divStats').html(view);
            }
        });
    }
</script>

Views/Player/_playerstats.cshtml
@model NBA_Stats.Models.SeasonAvgModel

@if (Model == null)
{
    <span>Stats unavailable for this season.</span>
}
else
{
    <div class="row">
        <div class="col-12">
            <div style="margin:0 auto;">
                <h3>Season Averages</h3>
                <div id="divSeasonStats">
                    Points: <span class="float-end">@Model.pts</span>

                    <hr style="margin:0" />
                    Rebounds: <span class="float-end">@Model.reb</span>
                    <hr style="margin:0" />
                    Assists: <span class="float-end">@Model.ast</span>
                    <hr style="margin:0" />
                    Steals: <span class="float-end">@Model.stl</span>
                    <hr style="margin:0" />
                    Blocks: <span class="float-end">@Model.blk</span>
                    <hr style="margin:0" />
                    FG%: <span class="float-end">@((Model.fg_pct * 100).ToString("0.#"))%</span>

                </div>
            </div>
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - NBA Stats</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
@*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">*@

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NBA_Stats.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/9be1aa850b.js" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NBA Stats</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Player_Search">Search Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Player_Comparison">Compare Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Justin McConchie</p>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>*@
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <script src="https://d3js.org/d3.v6.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Team/Index.cshtml
@{
    ViewBag.Title = "Teams";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<div class="row">
    <div class="col-lg-6">
        <h3>East</h3>
        <div id="eastContainer"></div>
    </div>

    <div class="col-lg-6">
        <h3>West</h3>
        <div id="westContainer"></div>
    </div>

</div>


@section Scripts{

    <script type="text/javascript">
    
        $(function(){
            $.ajax({
                type: "GET",
                url: 'https://www.balldontlie.io/api/v1/teams',
                success: function (data) {
                    //console.log(data);
                    data.data.forEach(team => addTeam(team));
                }
            });


        });
    
        function addTeam(team){

            let conferenceContainer = team.conference == "East" ? $('#eastContainer') : $('#westContainer');
            let teamURL = "/team/team_details/" + team.id;

                conferenceContainer.append(`<div><a href='` + teamURL + `'>` + team.full_name + `</a></div>`)

        }
    
    </script>



}